# Generated by Django 5.1.6 on 2025-02-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='student',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
