# Generated by Django 5.1.6 on 2025-02-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_students_student_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='parentsGuardians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'parents_guardians',
            },
        ),
    ]
