# Generated by Django 5.1.6 on 2025-02-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_parentsguardians'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='parentsGuardians',
            new_name='parentGuardian',
        ),
    ]
